spring:
  datasource:
    url: jdbc:mysql://192.168.1.216:3305/employee
    password: letmein
    username: root
    
  jpa:
    database-platform: org.springframework.arm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: -auto:update
      
    properties:
      hibernate:  
        globally_quoted_identifiers:true
        dialect:org.hibernate.dialect.MySQL8Dialect
        format_sql:true    